export const GET_ALL_NOTIFICATIONS = 'GET_ALL_NOTIFICATIONS'
export const GET_UNREAD_NOTIFICATIONS = 'GET_UNREAD_NOTIFICATIONS'
export const MARK_AS_READ_BY_ID = 'MARK_AS_READ_BY_ID'
export const ALL_MARK_AS_READ = 'ALL_MARK_AS_READ'