export const GET_SING_UP_GROUP_WORKOUTS_BY_ID = 'GET_SING_UP_GROUP_WORKOUTS_BY_ID';
export const ADD_SING_UP_GROUP_WORKOUT = 'ADD_SING_UP_GROUP_WORKOUT';
export const DELETE_SING_UP_GROUP_WORKOUT = 'DELETE_SING_UP_GROUP_WORKOUT';