export const GET_PERSONAL_SCHEDULES = 'GET_PERSONAL_SCHEDULES';
export const GET_PERSONAL_SCHEDULES_FOR_EDIT = 'GET_PERSONAL_SCHEDULES_FOR_EDIT';
export const ADD_SCHEDULE = 'ADD_SCHEDULE';
export const EDIT_SCHEDULE = 'EDIT_SCHEDULE';