export const GET_ALL_UNLIMITED_SUBSCRIPTIONS = 'GET_ALL_UNLIMITED_SUBSCRIPTIONS';
export const GET_UNLIMITED_SUBSCRIPTIONS = 'GET_UNLIMITED_SUBSCRIPTIONS';
export const ADD_UNLIMITED_SUBSCRIPTION = 'ADD_UNLIMITED_SUBSCRIPTION';
export const GET_ABOUT_SUBSCRIPTION = 'GET_ABOUT_SUBSCRIPTION';

