export const GET_GROUP_WORKOUTS = 'GET_GROUP_WORKOUTS';
export const GET_GROUP_WORKOUT_BY_ID = 'GET_GROUP_WORKOUT_BY_ID';
export const EDIT_GROUP_WORKOUT = 'EDIT_GROUP_WORKOUT';
export const FILTERING_GROUP_WORKOUTS = ' FILTERING_GROUP_WORKOUTS'
export const GET_GROUP_WORKOUTS_BY_SCHEDULE = ' GET_GROUP_WORKOUTS_BY_SCHEDULE';
export const GET_AVAILABLE_WORKOUTS = 'GET_AVAILABLE_WORKOUTS';
export const GET_SIGN_UP_WORKOUTS = 'GET_SIGN_UP_WORKOUTS';