
export const GET_ALL_LIMITED_PRICE_LISTS = 'GET_ALL_LIMITED_PRICE_LISTS';
export const GET_LIMITED_PRICE_LISTS = 'GET_LIMITED_PRICE_LISTS';
export const ADD_LIMITED_PRICE_LIST = 'ADD_LIMITED_PRICE_LIST';
