export const GET_ALL_CUSTOMERS = 'GET_ALL_CUSTOMERS';
export const GET_CUSTOMERS = 'GET_CUSTOMERS';
export const ADD_CUSTOMER = 'ADD_CUSTOMER';
export const EDIT_CUSTOMER = 'EDIT_CUSTOMER';
export const  VALIDATE_CUSTOMER = 'VALIDATE_CUSTOMER'